### ISSUE TITLE
can't find the image of turbopilot from ghcr.io

### ISSUE THREAD

**Issue by yinghanpeng** [ravenscroftj/turbopilot#14]
I can't find the image of turbopilot from ghcr.io,
I wonder what the problem is

![image](https://user-images.githubusercontent.com/22876733/232760353-ac1eaafc-a64a-4fa2-864b-f2328158d313.png)

Thank you in advance for your assistance!

**Comment by ravenscroftj** [comment]
Hi there - I believe you are looking at my dockerhub profile rather than my github profile - I don't know what tool you are using to look at the images but if you follow the instructions [here](https://github.com/ravenscroftj/turbopilot/pkgs/container/turbopilot/85802596?tag=latest) you should be able to grab the latest working image.
