### ISSUE TITLE
how to convert a new codegen model to ggml

### ISSUE THREAD

**Issue by czkoko** [ravenscroftj/turbopilot#15]
Because the  return time of the larger model is too long, I turned to codegen-350M.
And it only takes 1-2s to return the prompt code on my M1 computer.

I found a new codegen model on HF, it use codegen-350M-multi and finetuned on microsoft's codexglue.
[https://huggingface.co/ammarnasr/codegen-350M-multi-ft-on-code-x-glue-tc](https://huggingface.co/ammarnasr/codegen-350M-multi-ft-on-code-x-glue-tc)

I'll use the following py script to convert it to gpt-j first.
[codegen_gptj_convert.py.zip](https://github.com/ravenscroftj/turbopilot/files/11266200/codegen_gptj_convert.py.zip)

Then use convert-codegen-to-ggml.py

The model conversion was successful and loaded successfully, but codegen-serve only return "<|endoftext|>"

**Comment by ravenscroftj** [comment]
hey there - great question. I haven't had time to run this myself but I think the answer might be in the tokenizer. If the tokenizer is producing the wrong token id inputs it could lead the model to produce garbage or just not do anything.

On line 18 the script loads the tokenizer for the model that is being converted -

```python
print("Creating tokenizer")
tokenizer = CodeGenTokenizer.from_pretrained(args.code_model)
```
Now if you look in the [config.json](https://huggingface.co/ammarnasr/codegen-350M-multi-ft-on-code-x-glue-tc/blob/main/config.json) for the fine tuned model you see the tokenizer type is actually set to GPT2Tokenizer rather than CodeGenTokenizer. I don't know if it would be enough just to naively swap out the CodeGenTokenizer for a GPT2Tokenizer and run it again but maybe try that and post back?

**Comment by czkoko** [comment]
I tested other finetuned models with codegen_gptj_convert.py and succeeded, but the effect did not seem to be as good as the original codegen.

I noticed that `ammarnasr/codegen-350M-multi-ft-on-code-x-glue-tc` didn't seem to have finished training yet, and the state crashed.
[https://wandb.ai/ammarnasr/codegen_ft_on_codexglue/runs/a8h4vc2c/overview?workspace=user-](https://wandb.ai/ammarnasr/codegen_ft_on_codexglue/runs/a8h4vc2c/overview?workspace=user-)

**Comment by ravenscroftj** [comment]
Cool ok sounds like this is probably an incomplete/broken model so it isn't something that I'd be able to offer guidance on at present. Very happy to consider other models and architectures - I'm currently looking at [santacoder](https://huggingface.co/bigcode/santacoder) as a possible alternative.
