### ISSUE TITLE
I am new and Confused about the correct step for the section of "getting started"

### ISSUE THREAD

**Issue by RookyCoder** [ravenscroftj/turbopilot#17]
I am thrilled to see this local AI coding assistant but I am unsure some of the installation step and Your help is appreicated. 

![image](https://user-images.githubusercontent.com/129950420/233250513-bfaf69a7-61aa-4d6a-9dad-69c7d41e520b.png)

1.)Clone a copy of "main" of "turbopilot"  as  item no. I shown in the above figure.

2.) I go for Option A: Download pre-quantized models and paste it to the **models** folder in main, i choose 6B ~4GB as item no.II   and it looks like the same model in the example run command in step 4
![image](https://user-images.githubusercontent.com/129950420/233250267-713ce6aa-fe07-43bc-8555-0093936a22d4.png)

3.) Download binary of TurboPilot Server and extract it to the root project folder. 
![image](https://user-images.githubusercontent.com/129950420/233252986-bfba87cd-a041-4aca-b01c-289d777b8c4a.png)

4.) ./codegen-serve -t 6 -m ./models/codegen-6B-multi-ggml-4bit-quant.bin

I want to use it in VS Code with FauxPilot Plugin, also i am new to this too.
At the time of writing, it seems Venthe has accepted the PR so no need to install the "fauxpilot-1.1.5-ravenscroft.vsix" locally. Instead, _i can download the plugin directly_ in vs code extension market.

5. After install "fauxpilot Plug-in", Ctrl+Shift+P -  Preferences: Open User Settings (JSON)
![image](https://user-images.githubusercontent.com/129950420/233257068-e5b20f83-7050-40b8-8589-5bc7902b3acc.png)

================================= @ravenscroftj @
Q1: The suitable path of **turbopilot-main** ? Somewhere in Vscode folder such as installation path of fauxpilot?or Doesn't matter ?

Q2. _Adminstrator mode of Cmd:_ execute step 4? Has to be the root project folder path?
![image](https://user-images.githubusercontent.com/129950420/233256185-08b6c0e5-aa21-42c1-904b-37346a7d9c00.png)

<img width="947" alt="image" src="https://user-images.githubusercontent.com/129950420/233569641-8adf996b-4260-46c6-aba8-7daa62875112.png">

Same go to Q3   where to call it?
C:\    A     \     B   \Downloads\TurbopilotALL\turbopilot-main\turbopilot-main

Q3. difficulties about the calling the API directly? I have no idea about these mysterious code or command. But i assume that it can be called in web browser URL and talks to the recipient in root project folder?

_Running the requests in admin cmd_ http://localhost:18080/v1/engines/codegen/cohttp://localhost:18080/v1/engines/codegen/completions mpletions

Q4. Any confliction between other ai prompt offers similar feature or intelliSense that build in function in vs code? 

Thanks

**Comment by ravenscroftj** [comment]
Hi @RookyCoder  

I think the confusion is probably because I currently don't ship a windows version of turbocoder - I don't have a windows machine and haven't had time set up builds for windows - I might have a look over the weekend as it should be pretty straight forward given that llama.cpp does support windows.

When I add a codegen-serve.exe you'll just need to run that with the appropriate model name passed in.

You can call the API directly using any old HTTP client but I wouldn't recommend it as a beginner, you might as well stick to using Fauxpilot or similar.

There should not be any conflict between turbocoder and other features - Fauxpilot for VSCode uses the official VSCode extension points so it will complement other systems. I don't know if trying to use Fauxpilot and the official Copilot plugin at the same time would introduce some weirdness so I probably wouldn't recommend that.

I'll reply here again once I get windows builds working - although I don't have a windows machine so I'll have to rely on the community testing them for now.
